# Generated by Django 4.2.6 on 2023-10-09 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='region',
        ),
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='choice',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='step',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
